import { Geist, Geist_Mono, Urbanist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Common/Navbar/Navbar";
import FloatingNavbar from "../components/Common/Navbar/FloatingNavbar";
import Footer from "../components/Common/Footer/Footer";
import ScrollToTop from "../components/Common/ScrollToTop/ScrollToTop";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const bdoGrotesk = localFont({
  src: [
    {
      path: "./fonts/BDOGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/BDOGrotesk-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-bdo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import SmoothScroll from "../components/Common/SmoothScroll/SmoothScroll";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${urbanist.variable} ${bdoGrotesk.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col bg-black text-white" suppressHydrationWarning>
        <SmoothScroll>
          <Navbar />
          <main className="grow">
            {children}
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-4BP1MP000H"
              strategy="afterInteractive"
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-4BP1MP000H');
            `}
            </Script>
          </main>
          <Footer />
          <FloatingNavbar />
          <ScrollToTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
