import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Common/Navbar/Navbar";
import FloatingNavbar from "../components/Common/Navbar/FloatingNavbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        <Navbar />
        <main className="grow">
          {children}
        </main>
        <FloatingNavbar />
      </body>
    </html>
  );
}
